language: go

go:
  - 1.3
  - 1.2
  - release
  - tip

install:
  - export LD_LIBRARY_PATH="/usr/local/lib"
  - cd $HOME
  - git clone https://github.com/r9y9/world.git && cd world
  - git checkout v0.2.1-2
  - ./waf configure && ./waf
  - sudo ./waf install
  - cd $TRAVIS_BUILD_DIR

script:
 - go test -v --bench .
